package interfazBiblioteca;

 //@author Ivan

public class Pantallaprincipal extends jakarta.swing.JFrame {

    /**
     * Creates new form Pantallaprincipal
     */
   
    public Pantallaprincipal() {
        initComponents();
        
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new jakarta.swing.JMenuItem();
        jMenuItem2 = new jakarta.swing.JMenuItem();
        jMenuBar2 = new jakarta.swing.JMenuBar();
        jMenu3 = new jakarta.swing.JMenu();
        jMenu4 = new jakarta.swing.JMenu();
        jLabel1 = new jakarta.swing.JLabel();
        jPanel1 = new jakarta.swing.JPanel();
        jLabel2 = new jakarta.swing.JLabel();
        jLabel3 = new jakarta.swing.JLabel();
        jLabel4 = new jakarta.swing.JLabel();
        jLabel5 = new jakarta.swing.JLabel();
        jTextField1 = new jakarta.swing.JTextField();
        jLabel6 = new jakarta.swing.JLabel();
        jTextField2 = new jakarta.swing.JTextField();
        jRadioButton1 = new jakarta.swing.JRadioButton();
        jRadioButton2 = new jakarta.swing.JRadioButton();
        jLabel7 = new jakarta.swing.JLabel();
        jLabel8 = new jakarta.swing.JLabel();
        jPasswordField1 = new jakarta.swing.JPasswordField();
        jButton1 = new jakarta.swing.JButton();
        jButton2 = new jakarta.swing.JButton();
        jMenuBar1 = new jakarta.swing.JMenuBar();
        jMenu1 = new jakarta.swing.JMenu();
        jMenu2 = new jakarta.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(jakarta.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setIcon(new jakarta.swing.ImageIcon(getClass().getResource("/Imagenes/FondoBiblioteca.jpg"))); // NOI18N
        jLabel1.setText("jLabelPantalla");

        jLabel2.setIcon(new jakarta.swing.ImageIcon(getClass().getResource("/Imagenes/lampara.jpg"))); // NOI18N
        jLabel2.setBorder(jakarta.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jakarta.swing.GroupLayout jPanel1Layout = new jakarta.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(jakarta.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, jakarta.swing.GroupLayout.PREFERRED_SIZE, 659, jakarta.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(jakarta.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(jakarta.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, jakarta.swing.GroupLayout.PREFERRED_SIZE, 258, jakarta.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(402, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Sitka Text", 0, 36)); // NOI18N
        jLabel3.setText("Bievenido a la Página Principal");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel4.setText("¡Por favor, ingresá los datos del libro que deseas tomar prestado!");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Nombre del libro:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("ISBN del libro:");

        jRadioButton1.setText("Lo estoy regresando...");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Lo voy a llevar a casa...");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N
        jLabel7.setText("Confirmá lo que deseas hacer con el libro:");

        jLabel8.setText("DNI del estudiante:");

        jButton1.setBackground(new java.awt.Color(51, 255, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Enviar Formulario");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Salir de la pagina");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        jakarta.swing.GroupLayout layout = new jakarta.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(jakarta.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jakarta.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, jakarta.swing.GroupLayout.DEFAULT_SIZE, jakarta.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1723, 1723, 1723))
            .addGroup(jakarta.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(jakarta.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(jakarta.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, jakarta.swing.GroupLayout.PREFERRED_SIZE, 568, jakarta.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, jakarta.swing.GroupLayout.PREFERRED_SIZE, 479, jakarta.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(jakarta.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel6, jakarta.swing.GroupLayout.Alignment.LEADING, jakarta.swing.GroupLayout.DEFAULT_SIZE, jakarta.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, jakarta.swing.GroupLayout.Alignment.LEADING, jakarta.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(jakarta.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPasswordField1, jakarta.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8, jakarta.swing.GroupLayout.Alignment.LEADING, jakarta.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                .addComponent(jTextField2, jakarta.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField1, jakarta.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(jakarta.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton1, jakarta.swing.GroupLayout.PREFERRED_SIZE, 143, jakarta.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel7, jakarta.swing.GroupLayout.PREFERRED_SIZE, 332, jakarta.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)
                        .addGap(97, 97, 97)
                        .addComponent(jButton1)))
                .addPreferredGap(jakarta.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jLabel1, jakarta.swing.GroupLayout.PREFERRED_SIZE, 1705, jakarta.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(275, 275, 275))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(jakarta.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(jakarta.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, jakarta.swing.GroupLayout.PREFERRED_SIZE, 1073, jakarta.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, jakarta.swing.GroupLayout.PREFERRED_SIZE, 116, jakarta.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel4, jakarta.swing.GroupLayout.PREFERRED_SIZE, 64, jakarta.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, jakarta.swing.GroupLayout.PREFERRED_SIZE, 38, jakarta.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(jakarta.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, jakarta.swing.GroupLayout.PREFERRED_SIZE, jakarta.swing.GroupLayout.DEFAULT_SIZE, jakarta.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel6)
                        .addGap(30, 30, 30)
                        .addComponent(jTextField2, jakarta.swing.GroupLayout.PREFERRED_SIZE, jakarta.swing.GroupLayout.DEFAULT_SIZE, jakarta.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel8, jakarta.swing.GroupLayout.PREFERRED_SIZE, 30, jakarta.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPasswordField1, jakarta.swing.GroupLayout.PREFERRED_SIZE, jakarta.swing.GroupLayout.DEFAULT_SIZE, jakarta.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(jakarta.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, jakarta.swing.GroupLayout.PREFERRED_SIZE, 45, jakarta.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(jakarta.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton1)
                        .addPreferredGap(jakarta.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(jakarta.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton1))))
                .addPreferredGap(jakarta.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, jakarta.swing.GroupLayout.PREFERRED_SIZE, jakarta.swing.GroupLayout.DEFAULT_SIZE, jakarta.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(jakarta.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        Pantalla Registrousuario = new Pantalla();
      Registrousuario.setVisible(true);
      
      Registrousuario.setLocationRelativeTo(null);
      this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
       Tabladatos Registrousuario = new Tabladatos();
      Registrousuario.setVisible(true);
      
      Registrousuario.setLocationRelativeTo(null);
      this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private jakarta.swing.JButton jButton1;
    private jakarta.swing.JButton jButton2;
    private jakarta.swing.JLabel jLabel1;
    private jakarta.swing.JLabel jLabel2;
    private jakarta.swing.JLabel jLabel3;
    private jakarta.swing.JLabel jLabel4;
    private jakarta.swing.JLabel jLabel5;
    private jakarta.swing.JLabel jLabel6;
    private jakarta.swing.JLabel jLabel7;
    private jakarta.swing.JLabel jLabel8;
    private jakarta.swing.JMenu jMenu1;
    private jakarta.swing.JMenu jMenu2;
    private jakarta.swing.JMenu jMenu3;
    private jakarta.swing.JMenu jMenu4;
    private jakarta.swing.JMenuBar jMenuBar1;
    private jakarta.swing.JMenuBar jMenuBar2;
    private jakarta.swing.JMenuItem jMenuItem1;
    private jakarta.swing.JMenuItem jMenuItem2;
    private jakarta.swing.JPanel jPanel1;
    private jakarta.swing.JPasswordField jPasswordField1;
    private jakarta.swing.JRadioButton jRadioButton1;
    private jakarta.swing.JRadioButton jRadioButton2;
    private jakarta.swing.JTextField jTextField1;
    private jakarta.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

}
